import { ProductCategory } from './types';

export const COMPANY_INFO = {
  name: 'BIRLIK COMPANY İNŞAAT SAN. VE TİC. LTD. ŞTİ.',
  taxId: '1781414783',
  phone: '+90 530 368 98 34',
  whatsappNumber: '905303689834',
  email: 'info@birlik-insaat.com',
  address: 'Akdeniz Mah. 39716 Sk. Özgül 2 Apt. No: 10/1A, Mezitli, Mersin, Türkiye',
  workingHours: 'Pazartesi - Cuma: 09:00 - 18:00',
  mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3198.240316489345!2d34.5368583156209!3d36.7169439799653!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15278a5b2f2f2f2f%3A0x1c1c1c1c1c1c1c1c!2sAkdeniz%2C%2039716.%20Sk.%20No%3A10%2C%2033340%20Mezitli%2FMersin%2C%20Turkey!5e0!3m2!1sen!2sus!4v1622038311933!5m2!1sen!2sus', // Example embed URL
  instagramUrl: 'https://www.instagram.com/birlik.company_/',
  facebookUrl: 'https://www.facebook.com/p/Birlik-company-61560270204237/',
  linkedinUrl: 'https://www.linkedin.com/company/birlik-company/',
};

export const translations = {
  tr: {
    language: 'Türkçe',
    home: 'Anasayfa',
    products: 'Ürünler',
    contact: 'İletişim',
    calculator: 'Hesaplayıcı',
    calculateNeeds: 'İhtiyacını Hesapla',
    categories: 'Ürün Kategorileri',
    viewProducts: 'Ürünleri Gör',
    allRightsReserved: 'Tüm hakları saklıdır.',
    [ProductCategory.PS_FLUTED]: 'PS Duvar Lambirileri',
    [ProductCategory.PVC_UV_MARBLE]: 'PVC Mermer Levhalar',
    [ProductCategory.PS_BASEBOARD]: 'PS Süpürgelikler',
    [ProductCategory.PS_MOLDING]: 'PS Duvar Çıtaları',
    [ProductCategory.PU_MOTIF]: 'Poliüretan Motifler',
    getQuoteOnWhatsApp: "WhatsApp'tan Teklif Al",
    heroTitle: 'Mekanlarınıza Değer Katan Çözümler',
    heroSubtitle: 'Yüksek kaliteli duvar panelleri, süpürgelikler ve dekoratif motiflerle estetiği ve dayanıklılığı bir araya getiriyoruz.',
    exploreProducts: 'Ürünleri Keşfet',
    bestSellers: 'Çok Satanlar',
    ourMission: 'Misyonumuz',
    missionText: 'Birlik Company olarak misyonumuz; estetik, fonksiyonellik ve sürdürülebilirliği bir araya getiren yenilikçi ve yüksek kaliteli iç mekân kaplama çözümleriyle müşteri memnuniyetini en üst düzeye çıkarmaktır. Türkiye ve Orta Doğu’ya odaklanarak, bölgemizin ihtiyaçlarına uygun sürdürülebilir malzemeleri keşfedip yerelleştiriyoruz. Sürekli Ar-Ge çalışmalarımızla çözüm ve ürün portföyümüzü durmaksızın geliştiriyor; inşaat ve dekorasyon sektöründe standartları yükselterek mekânları güzel, dayanıklı ve sorumlu kılıyoruz.',
    newsletterTitle: 'Haber Bültenimize Kaydolun',
    newsletterSubtitle: 'Yeni ürünler ve özel tekliflerden ilk siz haberdar olun.',
    emailPlaceholder: 'E-posta adresiniz',
    subscribe: 'Abone Ol',
    contactUs: 'Bize Ulaşın',
    goBack: 'Geri Dön',
    productDetails: 'Ürün Detayları',
    material: 'Materyal',
    width: 'Genişlik',
    heightLength: 'Uzunluk/Yükseklik',
    thickness: 'Kalınlık',
    packSize: 'Paket Adedi',
    surface: 'Yüzey',
    unitPieces: 'adet',
    searchProducts: 'Ürünleri ara...',
    // Contact Page
    getInTouch: 'İletişime Geçin',
    contactIntro: 'Sorularınız, işbirliği teklifleriniz veya ürünlerimiz hakkında daha fazla bilgi için bize ulaşmaktan çekinmeyin.',
    yourName: 'Adınız',
    yourEmail: 'E-posta Adresiniz',
    yourMessage: 'Mesajınız',
    sendMessage: 'Mesaj Gönder',
    phoneLabel: 'Tel/WhatsApp',
    emailLabel: 'Email',
    addressLabel: 'Adres',
    workingHoursLabel: 'Çalışma Saatleri',
    workingHoursValue: 'Pazartesi - Cuma: 09:00 - 18:00',
    bookConsultationTitle: 'Ücretsiz Danışmanlık Randevusu Alın',
    bookConsultationSubtitle: 'Uzmanlarımız projeniz için en iyi ürünleri seçmenize yardımcı olmaya hazır. Hızlı bir görüşme için WhatsApp\'tan bize ulaşın.',
    contactOnWhatsApp: 'WhatsApp\'tan İletişime Geç',
    whatsappConsultationMessage: 'Merhaba, ürünlerinizle ilgili bir danışmanlık randevusu almak istiyorum.',
    // Polymer Features
    polymerProductFeatures: 'Polimer Ürün Özellikleri',
    polymerProductFeatures_subtitle: 'Ürünlerimizi endüstri lideri yapan temel özelliklerini keşfedin. Dayanıklılık, estetik ve kullanım kolaylığı için tasarlandı.',
    feature_polymer_formula_title: 'POLİMER FORMÜL',
    feature_polymer_formula_desc: 'Birlik Company özel polimer formül kullanılmaktadır.',
    feature_paintable_title: 'BOYANABİLİR',
    feature_paintable_desc: 'Beyaz yüzeyli ürünlerimiz, istediğiniz renge boyanabilen bir yapıya sahiptir.',
    feature_easy_installation_title: 'KOLAY MONTAJ',
    feature_easy_installation_desc: 'Birbirine geçmeli yapısı ile kolay bir şekilde monte edilir.',
    feature_antibacterial_title: 'ANTİBAKTERİYEL',
    feature_antibacterial_desc: 'Küf, mantar, bakteri gibi zararlılara karşı dayanıklıdır.',
    feature_cutable_title: 'KESİLEBİLİR',
    feature_cutable_desc: 'Polimer yapısı sayesinde istenilen ölçülerde kolayca kesilebilir.',
    feature_water_resistant_title: 'SUYA VE NEME DAYANIKLI',
    feature_water_resistant_desc: 'Folyo kaplaması ve sert dış yüzeyi sayesinde suya ve neme karşı tam koruma sağlar.',
    feature_adhesive_title: 'YAPIŞTIRILABİLİR',
    feature_adhesive_desc: 'Silikon mastik sayesinde uygulamak istediğiniz yüzeye kolayca yapıştırabilirsiniz.',
    feature_eco_friendly_title: 'ÇEVRE DOSTU',
    feature_eco_friendly_desc: 'Canlılara karşı zararı yoktur. Hijyeniktir ve kötü koku yaymaz.',
    feature_impact_resistant_title: 'DARBEYE DAYANIKLI',
    feature_impact_resistant_desc: 'Sert dış yüzeyi ve esnek yapısı ile darbelere karşı dayanıklıdır.',
    feature_recyclable_title: 'GERİ DÖNÜŞTÜRÜLEBİLİR',
    feature_recyclable_desc: 'Kullanım ömrü bittiğinde yeni ürünler yapmak için geri dönüştürülebilir.',
    // Surface Finishes
    uvMat: 'UV MAT',
    reflective: 'Yansıtıcı',
    woodLook: 'Ahşap Görünüm',
    glossy: 'Parlak',
    matteWhite: 'Mat Beyaz',
    paintable: 'Boyanabilir',
    // Calculator
    calculatorIntro: 'Tek bir alan için hızlı hesaplayıcılarımızı kullanın veya birden fazla duvar ve ürün için plan yapmak üzere Proje Hesaplayıcı\'ya gidin.',
    productCalculators: 'Hızlı Miktar Hesaplayıcıları',
    projectCalculatorTitle: 'Proje Hesaplayıcı',
    projectSummary: 'Proje Özeti',
    addWallArea: 'Duvar/Alan Ekle',
    remove: 'Kaldır',
    wallAreaName: 'Duvar/Alan Adı (Opsiyonel)',
    selectProduct: 'Ürün Seçiniz',
    noItems: 'Projenize başlamak için bir duvar veya alan ekleyin.',
    totalRequired: 'Toplam Gerekli',
    quantityCalculator: 'Miktar Hesaplayıcı',
    calculate: 'Hesapla',
    result: 'Sonuç',
    wastePercentage: 'Fire Payı (%)',
    wallWidth: 'Duvar Genişliği (cm)',
    wallHeight: 'Duvar Yüksekliği (cm)',
    areaWidth: 'Alan Genişliği (cm)',
    areaHeight: 'Alan Yüksekliği (cm)',
    totalWallLength: 'Toplam Duvar Uzunluğu (cm)',
    frameWidth: 'Çerçeve Genişliği (cm)',
    frameHeight: 'Çerçeve Yüksekliği (cm)',
    whatsappProjectQuoteIntro: 'Merhaba, proje hesaplayıcımdan çıkan aşağıdaki ürünler için bir teklif almak istiyorum:',
    getProjectQuoteOnWhatsApp: 'Proje Teklifi Al (WhatsApp)',
    // Outputs
    requiredPieces: 'Gereken Parça Sayısı',
    offcutPerPiece: 'Parça Başına Artan',
    totalOffcut: 'Toplam Artan Uzunluk',
    requiredSheets: 'Gereken Levha Sayısı',
    totalWaste: 'Toplam Fire',
    totalPerimeter: 'Toplam Çevre Uzunluğu',
    // Notes & Warnings
    heightWarning: 'Duvar yüksekliği panel uzunluğundan fazla. Lütfen eklemeler için plan yapın.',
    baseboardTip: 'İpucu: Artan parçaları başka bir duvarın başlangıcında kullanarak fireyi azaltabilirsiniz.',
    moldingNote: 'Not: Bu hesaplama, belirtilen ölçülerde bir çerçeve için gereken toplam çıta uzunluğunu baz alır.',
    compatibleMolding: 'Uyumlu Çıta Modeli',
  },
  en: {
    language: 'English',
    home: 'Home',
    products: 'Products',
    contact: 'Contact',
    calculator: 'Calculator',
    calculateNeeds: 'Calculate Needs',
    categories: 'Product Categories',
    viewProducts: 'View Products',
    allRightsReserved: 'All rights reserved.',
    [ProductCategory.PS_FLUTED]: 'PS Fluted Panels',
    [ProductCategory.PVC_UV_MARBLE]: 'PVC Marble Sheets',
    [ProductCategory.PS_BASEBOARD]: 'PS Baseboards',
    [ProductCategory.PS_MOLDING]: 'PS Wall Moldings',
    [ProductCategory.PU_MOTIF]: 'Polyurethane Motifs',
    getQuoteOnWhatsApp: 'Get a Quote on WhatsApp',
    heroTitle: 'Solutions That Add Value to Your Spaces',
    heroSubtitle: 'We bring together aesthetics and durability with high-quality wall panels, baseboards, and decorative motifs.',
    exploreProducts: 'Explore Products',
    bestSellers: 'Best Sellers',
    ourMission: 'Our Mission',
    missionText: 'At Birlik Company, our mission is to maximize customer satisfaction by delivering innovative, high-quality interior finishing solutions that unite aesthetics, functionality, and sustainability. Focused on Türkiye and the Middle East, we actively discover and localize sustainable materials for our region. Through relentless research and development, we continuously upgrade and expand our roster of solutions—raising standards in the construction and decoration sector and creating spaces that are beautiful, durable, and responsible.',
    newsletterTitle: 'Subscribe to Our Newsletter',
    newsletterSubtitle: 'Be the first to know about new products and special offers.',
    emailPlaceholder: 'Your email address',
    subscribe: 'Subscribe',
    contactUs: 'Contact Us',
    goBack: 'Go Back',
    productDetails: 'Product Details',
    material: 'Material',
    width: 'Width',
    heightLength: 'Height/Length',
    thickness: 'Thickness',
    packSize: 'Pack Size',
    surface: 'Surface',
    unitPieces: 'pieces',
    searchProducts: 'Search products...',
    // Contact Page
    getInTouch: 'Get In Touch',
    contactIntro: 'Feel free to contact us for your questions, collaboration proposals or for more information about our products.',
    yourName: 'Your Name',
    yourEmail: 'Your Email Address',
    yourMessage: 'Your Message',
    sendMessage: 'Send Message',
    phoneLabel: 'Phone/WhatsApp',
    emailLabel: 'Email',
    addressLabel: 'Address',
    workingHoursLabel: 'Working Hours',
    workingHoursValue: 'Monday - Friday: 09:00 - 18:00',
    bookConsultationTitle: 'Book a Free Consultation',
    bookConsultationSubtitle: 'Our experts are ready to help you choose the best products for your project. Contact us on WhatsApp for a quick chat.',
    contactOnWhatsApp: 'Contact on WhatsApp',
    whatsappConsultationMessage: 'Hello, I would like to book a consultation regarding your products.',
    // Polymer Features
    polymerProductFeatures: 'Polymer Product Features',
    polymerProductFeatures_subtitle: 'Discover the core features that make our products industry leaders. Designed for durability, aesthetics, and ease of use.',
    feature_polymer_formula_title: 'POLYMER FORMULA',
    feature_polymer_formula_desc: 'Birlik Company uses a special polymer formula.',
    feature_paintable_title: 'PAINTABLE',
    feature_paintable_desc: 'Our products with a white surface have a structure that can be painted to any desired color.',
    feature_easy_installation_title: 'EASY INSTALLATION',
    feature_easy_installation_desc: 'It is easily assembled with its interlocking structure.',
    feature_antibacterial_title: 'ANTIBACTERIAL',
    feature_antibacterial_desc: 'It is resistant to pests such as mold, fungus, and bacteria.',
    feature_cutable_title: 'CUTABLE',
    feature_cutable_desc: 'It can be easily cut to desired sizes thanks to its polymer structure.',
    feature_water_resistant_title: 'WATER & MOISTURE RESISTANT',
    feature_water_resistant_desc: 'Its foil coating and hard outer surface provide full protection against water and moisture.',
    feature_adhesive_title: 'ADHESIVE',
    feature_adhesive_desc: 'Thanks to silicone sealant, you can easily stick it to the surface you want to apply it to.',
    feature_eco_friendly_title: 'ENVIRONMENTALLY FRIENDLY',
    feature_eco_friendly_desc: 'It is harmless to living beings. It is hygienic and does not emit bad odor.',
    feature_impact_resistant_title: 'IMPACT RESISTANT',
    feature_impact_resistant_desc: 'It absorbs impact with its hard outer surface and flexible structure.',
    feature_recyclable_title: 'RECYCLABLE',
    feature_recyclable_desc: 'Once its lifespan is over, it can be processed to make new products.',
    // Surface Finishes
    uvMat: 'UV MAT',
    reflective: 'Reflective',
    woodLook: 'Wood Look',
    glossy: 'Glossy',
    matteWhite: 'Matte White',
    paintable: 'Paintable',
    // Calculator
    calculatorIntro: 'Use our quick calculators for a single area, or scroll down to the Project Calculator to plan for multiple walls and products.',
    productCalculators: 'Quick Quantity Calculators',
    projectCalculatorTitle: 'Project Calculator',
    projectSummary: 'Project Summary',
    addWallArea: 'Add Wall / Area',
    remove: 'Remove',
    wallAreaName: 'Wall/Area Name (Optional)',
    selectProduct: 'Select a Product',
    noItems: 'Add a wall or area to start your project.',
    totalRequired: 'Total Required',
    quantityCalculator: 'Quantity Calculator',
    calculate: 'Calculate',
    result: 'Result',
    wastePercentage: 'Waste Percentage (%)',
    wallWidth: 'Wall Width (cm)',
    wallHeight: 'Wall Height (cm)',
    areaWidth: 'Area Width (cm)',
    areaHeight: 'Area Height (cm)',
    totalWallLength: 'Total Wall Length (cm)',
    frameWidth: 'Frame Width (cm)',
    frameHeight: 'Frame Height (cm)',
    whatsappProjectQuoteIntro: 'Hello, I would like to get a quote for the following items from my project calculation:',
    getProjectQuoteOnWhatsApp: 'Get Project Quote (WhatsApp)',
    // Outputs
    requiredPieces: 'Required Pieces',
    offcutPerPiece: 'Offcut per Piece',
    totalOffcut: 'Total Offcut Length',
    requiredSheets: 'Required Sheets',
    totalWaste: 'Total Waste',
    totalPerimeter: 'Total Perimeter Length',
    // Notes & Warnings
    heightWarning: 'Wall height exceeds panel length. Please plan for joints.',
    baseboardTip: 'Tip: You can reduce waste by using the offcut from one wall to start the next.',
    moldingNote: 'Note: This calculation is based on the total molding length required for one frame of the specified dimensions.',
    compatibleMolding: 'Compatible Molding Model',
  },
  ar: {
    language: 'العربية',
    home: 'الرئيسية',
    products: 'المنتجات',
    contact: 'اتصل بنا',
    calculator: 'حاسبة',
    calculateNeeds: 'احسب احتياجك',
    categories: 'فئات المنتجات',
    viewProducts: 'عرض المنتجات',
    allRightsReserved: 'كل الحقوق محفوظة.',
    [ProductCategory.PS_FLUTED]: 'بديل الخشب',
    [ProductCategory.PVC_UV_MARBLE]: 'بديل الرخام',
    [ProductCategory.PS_BASEBOARD]: 'نعلات فوم',
    [ProductCategory.PS_MOLDING]: 'إطارات فوم',
    [ProductCategory.PU_MOTIF]: 'زخارف بولي يوريثان',
    getQuoteOnWhatsApp: 'احصل على عرض عبر واتساب',
    heroTitle: 'حلول تضيف قيمة لمساحاتك',
    heroSubtitle: 'نجمع بين الجمال والمتانة مع ألواح الجدران عالية الجودة، والنعلات، والزخارف.',
    exploreProducts: 'اكتشف المنتجات',
    bestSellers: 'الأكثر مبيعاً',
    ourMission: 'مهمتنا',
    missionText: 'في شركة بيرليك، تتمثّل رسالتنا في تعظيم رضا العملاء عبر تقديم حلول تشطيبات داخلية مبتكرة وعالية الجودة تجمع بين الجمال والوظيفية والاستدامة. ومع تركيزنا على تركيا ومنطقة الشرق الأوسط، نكتشف المواد المستدامة ونوطّنها بما يلائم احتياجات منطقتنا. وبفضل البحث والتطوير المتواصلين، نُطوِّر ونوسّع باستمرار محفظة حلولنا ومنتجاتنا، لنرفع معايير قطاع الإنشاء والديكور ونصنع مساحاتٍ جميلة، متينة، ومسؤولة.',
    newsletterTitle: 'اشترك في نشرتنا الإخبارية',
    newsletterSubtitle: 'كن أول من يعرف عن المنتجات الجديدة والعروض الخاصة.',
    emailPlaceholder: 'عنوان بريدك الإلكتروني',
    subscribe: 'اشتراك',
    contactUs: 'اتصل بنا',
    goBack: 'العودة',
    productDetails: 'تفاصيل المنتج',
    material: 'المادة',
    width: 'العرض',
    heightLength: 'الارتفاع/الطول',
    thickness: 'السماكة',
    packSize: 'حجم العبوة',
    surface: 'السطح',
    unitPieces: 'قطع',
    searchProducts: 'ابحث عن المنتجات...',
    // Contact Page
    getInTouch: 'ابقى على تواصل',
    contactIntro: 'لا تتردد في الاتصال بنا لطرح أسئلتك أو مقترحات التعاون أو لمزيد من المعلومات حول منتجاتنا.',
    yourName: 'اسمك',
    yourEmail: 'عنوان بريدك الإلكتروني',
    yourMessage: 'رسالتك',
    sendMessage: 'إرسال رسالة',
    phoneLabel: 'الهاتف/واتساب',
    emailLabel: 'البريد الإلكتروني',
    addressLabel: 'العنوان',
    workingHoursLabel: 'ساعات العمل',
    workingHoursValue: 'الاثنين - الجمعة: 09:00 - 18:00',
    bookConsultationTitle: 'احجز استشارة مجانية',
    bookConsultationSubtitle: 'خبراؤنا مستعدون لمساعدتك في اختيار أفضل المنتجات لمشروعك. تواصل معنا عبر واتساب لمحادثة سريعة.',
    contactOnWhatsApp: 'تواصل عبر واتساب',
    whatsappConsultationMessage: 'مرحباً، أود حجز استشارة بخصوص منتجاتكم.',
    // Polymer Features
    polymerProductFeatures: 'ميزات منتجات البوليمر',
    polymerProductFeatures_subtitle: 'اكتشف الميزات الأساسية التي تجعل منتجاتنا رائدة في الصناعة. مصممة للمتانة والجمال وسهولة الاستخدام.',
    feature_polymer_formula_title: 'تركيبة البوليمر',
    feature_polymer_formula_desc: 'تستخدم شركة Birlik Company تركيبة بوليمر خاصة.',
    feature_paintable_title: 'قابل للدهان',
    feature_paintable_desc: 'منتجاتنا ذات السطح الأبيض لها هيكل يمكن طلاؤه بأي لون مرغوب.',
    feature_easy_installation_title: 'تركيب سهل',
    feature_easy_installation_desc: 'يتم تجميعه بسهولة بفضل هيكله المتشابك.',
    feature_antibacterial_title: 'مضاد للبكتيريا',
    feature_antibacterial_desc: 'مقاوم للآفات مثل العفن والفطريات والبكتيريا.',
    feature_cutable_title: 'قابل للقطع',
    feature_cutable_desc: 'يمكن قصه بسهولة إلى الأحجام المرغوبة بفضل هيكله البوليمري.',
    feature_water_resistant_title: 'مقاوم للماء والرطوبة',
    feature_water_resistant_desc: 'يوفر طلاءه ورقائقه وسطحه الخارجي الصلب حماية كاملة ضد الماء والرطوبة.',
    feature_adhesive_title: 'قابل للصق',
    feature_adhesive_desc: 'بفضل مادة السيليكون اللاصقة، يمكنك لصقه بسهولة على السطح الذي تريده.',
    feature_eco_friendly_title: 'صديق للبيئة',
    feature_eco_friendly_desc: 'غير ضار بالكائنات الحية. صحي ولا يصدر رائحة سيئة.',
    feature_impact_resistant_title: 'مقاوم للصدمات',
    feature_impact_resistant_desc: 'يمتص الصدمات بسطحه الخارجي الصلب وهيكله المرن.',
    feature_recyclable_title: 'قابل لإعادة التدوير',
    feature_recyclable_desc: 'عندما ينتهي عمره الافتراضي، يمكن معالجته لصنع منتجات جديدة.',
    // Surface Finishes
    uvMat: 'UV MAT',
    reflective: 'عاكس',
    woodLook: 'مظهر خشبي',
    glossy: 'لامع',
    matteWhite: 'أبيض مطفي',
    paintable: 'قابل للدهن',
    // Calculator
    calculatorIntro: 'استخدم حاسباتنا السريعة لمنطقة واحدة، أو انتقل إلى حاسبة المشروع للتخطيط لجدران ومنتجات متعددة.',
    productCalculators: 'حاسبات الكمية السريعة',
    projectCalculatorTitle: 'حاسبة المشروع',
    projectSummary: 'ملخص المشروع',
    addWallArea: 'أضف جدار / منطقة',
    remove: 'إزالة',
    wallAreaName: 'اسم الجدار/المنطقة (اختياري)',
    selectProduct: 'اختر منتجًا',
    noItems: 'أضف جدارًا أو منطقة لبدء مشروعك.',
    totalRequired: 'إجمالي المطلوب',
    quantityCalculator: 'حاسبة الكمية',
    calculate: 'احسب',
    result: 'النتيجة',
    wastePercentage: 'نسبة الهدر (%)',
    wallWidth: 'عرض الجدار (سم)',
    wallHeight: 'ارتفاع الجدار (سم)',
    areaWidth: 'عرض المنطقة (سم)',
    areaHeight: 'ارتفاع المنطقة (سم)',
    totalWallLength: 'إجمالي طول الجدار (سم)',
    frameWidth: 'عرض الإطار (سم)',
    frameHeight: 'ارتفاع الإطار (سم)',
    whatsappProjectQuoteIntro: 'مرحباً، أود الحصول على عرض أسعار للمنتجات التالية من حاسبة المشروع الخاصة بي:',
    getProjectQuoteOnWhatsApp: 'احصل على عرض أسعار المشروع (واتساب)',
    // Outputs
    requiredPieces: 'القطع المطلوبة',
    offcutPerPiece: 'القصاصة لكل قطعة',
    totalOffcut: 'إجمالي طول القصاصات',
    requiredSheets: 'الألواح المطلوبة',
    totalWaste: 'إجمالي الهدر',
    totalPerimeter: 'إجمالي طول المحيط',
    // Notes & Warnings
    heightWarning: 'ارتفاع الجدار يتجاوز طول اللوح. يرجى التخطيط للوصلات.',
    baseboardTip: 'نصيحة: يمكنك تقليل الهدر باستخدام قصاصة من جدار لبدء الجدار التالي.',
    moldingNote: 'ملاحظة: يعتمد هذا الحساب على إجمالي طول الإطار المطلوب لإطار واحد بالأبعاد المحددة.',
    compatibleMolding: 'طراز الإطار المتوافق',
  },
};